<a href="https://colab.research.google.com/github/EidMuhammadlaghari/Data_science/blob/main/20sw009__lab_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Roll number: 20sw009**
**Section: 01**
**lab: 04**

Task 1

In [1]:
import numpy as np

#using the range function to generate the even numbers
e_num = np.arange(2, 34, 2)

X = e_num.reshape(4, 4)

print(X)


[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


Task 2

In [2]:
import numpy as np

# Create a 5 x 5 ndarray with consecutive integers from 1 to 25
X = np.arange(1, 26).reshape(5, 5)

# Use Boolean indexing to pick out only the odd numbers
Y = X[X % 2 != 0]

#printing the origenal array
print("Original array X:\n", X)

#printing the odd numbers
print("\nArray Y with odd numbers:\n", Y)

Original array X:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Array Y with odd numbers:
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25]


Task 3

In [3]:
import numpy as np

# Creating a 4 x 4 ndarray with columns of consecutive numbers
X = np.arange(1, 5)

# Using broadcasting to create the desired array
X = X[:, np.newaxis] * np.ones((1, 4), dtype=int)

#printing the array
print(X)

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]


Task 4

In [5]:
import numpy as np

# Creating a 1000 x 20 ndarray with random integers in the interval [0, 5001)
X = np.random.randint(0, 5001, size=(1000, 20))

# Print the shape of X
print(X.shape)

# Calculating the average (mean) of the values in each column
ave_cols = np.mean(X, axis=0)

# Calculating the standard deviation of the values in each column
std_cols = np.std(X, axis=0)

print("Average of values in each column:", ave_cols)

print("Standard Deviation of values in each column:", std_cols)

# Calculating the average (mean) of the values in each column
ave_cols = np.mean(X, axis=0)

# Calculating the standard deviation of the values in each column
std_cols = np.std(X, axis=0)

# Printing the shape of ave_cols and std_cols
print("Shape of ave_cols:", ave_cols.shape)

print("Shape of std_cols:", std_cols.shape)

# Mean normalize X
X_norm = (X - np.mean(X, axis=0)) / np.std(X, axis=0)

# Printing the average of all the values of X_norm
ave_X_norm = np.mean(X_norm)
print("Average of all values in X_norm:", ave_X_norm)

# Printing the average of the minimum value in each column of X_norm
ave_min_X_norm = np.mean(np.min(X_norm, axis=0))
print("Average of minimum value in each column of X_norm:", ave_min_X_norm)

# Printing the average of the maximum value in each column of X_norm
ave_max_X_norm = np.mean(np.max(X_norm, axis=0))
print("Average of maximum value in each column of X_norm:", ave_max_X_norm)


# Creating a random permutation of integers 0 to 4
permuted_indices = np.random.permutation(5)

# Creating a rank 1 ndarray that contains a random permutation of the row indices of X_norm
row_indices = np.random.permutation(X_norm.shape[0])

# Shuffling the rows of X_norm according to the random permutation
X_norm_shuffled = X_norm[row_indices]

# Calculating the number of examples in each set
num_examples = X_norm.shape[0]
num_train = int(0.7 * num_examples)   # 70% for training
num_crossVal = int(0.15 * num_examples)   # 15% for cross-validation
num_test = num_examples - num_train - num_crossVal   # Remaining 15% for testing

# Creating a Training Set
X_train = X_norm_shuffled[:num_train]

# Creating a Cross Validation Set
X_crossVal = X_norm_shuffled[num_train:num_train + num_crossVal]

# Creating a Test Set
X_test = X_norm_shuffled[num_train + num_crossVal:]

# Priningt the shape of X_train
print("Shape of X_train:", X_train.shape)

# Printing the shape of X_crossVal
print("Shape of X_crossVal:", X_crossVal.shape)

# Printing the shape of X_test
print("Shape of X_test:", X_test.shape)



(1000, 20)
Average of values in each column: [2504.967 2498.285 2513.123 2464.284 2431.385 2562.119 2523.69  2471.88
 2457.778 2503.535 2529.716 2541.016 2515.646 2553.699 2403.221 2373.31
 2456.208 2516.585 2590.393 2553.117]
Standard Deviation of values in each column: [1421.51795976 1456.41301346 1412.0555888  1445.96232155 1435.09928185
 1426.94215469 1455.93001065 1443.40940609 1452.92365344 1428.11701719
 1446.92664892 1445.78575582 1435.39051087 1407.28393738 1454.39704419
 1388.0620735  1437.62367146 1462.2351886  1435.21001549 1427.53263546]
Shape of ave_cols: (20,)
Shape of std_cols: (20,)
Average of all values in X_norm: -2.9842794901924206e-17
Average of minimum value in each column of X_norm: -1.737802758429676
Average of maximum value in each column of X_norm: 1.7393989365940925
